fix problem with hadoop2 detection

diff --git a/src/main/shell/hadoop-env b/src/main/shell/hadoop-env
--- a/src/main/shell/hadoop-env
+++ b/src/main/shell/hadoop-env
@@ -8,5 +8,12 @@ if [ -z "${HADOOP_HOME}" ]; then
     exit 1
   fi
 else
-    export HADOOP_EXEC="$HADOOP_HOME/bin/hadoop"
+    BIN_PATH="$HADOOP_HOME/bin/hadoop"
+    if [ -n "${BIN_PATH}" ] ; then
+      export HADOOP_EXEC=$BIN_PATH
+      return
+    else
+      echo "Could not find HADOOP_HOME nor is 'hadoop' in the PATH. exiting."
+      exit 1
+  fi
 fi
